name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@YOUR_EC2_IP_ADDRESS << 'EOF'
          cd /var/www/app
          
          # Pull the latest code
          git pull origin main

          # Install dependencies
          npm install --production

          # Check if PM2 is running, start if not, otherwise restart
          if pm2 list | grep -q "CICID-APP"; then
            pm2 restart CICID-APP
          else
            pm2 start server.js --name CICID-APP
          fi
          EOF
